### ISSUE TITLE
Implement Reporter Registation

### ISSUE THREAD

**Issue by steveshortt** [SynapseProject/Syntinel.Design#6]
- Reporter should "register" with Relay tier, provide "registration id" on all signal messages.
- Subscribers would use "registration id" as well as other "filter criterion" to specify which messages to receive.
- Add "Reporter Validation" to Relay Tier.

**Comment by GuyWaguespack** [comment]
Added base implementation.   Still need to : 
- Add "trace" information into signal message.
- Add routing information to CloudWatch logs (print)
- Develop API to Create / Delete / Modify reporter info.
